addons:
  ssh_known_hosts: 217.70.189.97

env:
- secure: stMKPVRThfcQJfLYz9y5eTxou6Zu9PVxpsatzzEZiOTIhkkAm6BWgkIFmf9LGy6A8iIbQZIWZqbtNhzOMi0of2Hg2/Zh+nOfnbwBtdRen5QmpGSFpOJRtCsekXlnRgCEJnHmitbZe+8TMIqpYg1yPcmHxZDj+tUsKo0VM2HqIbBWLxRORX+Q5momb8WHlynWF3/71ID5so0H1oApkJKeUQRCkOxwZkHibeYVKieH4vIC9AAouNupYLCx7151gjm6FWisDKj8s4+Y07OzJSJPhYpnLapZA0CdB0ldIHtzxtxaA72kXjyY/k8IOEQPqK6A2diEksMaAxI/9Htbn8HkSsMOmS7DqHvRvQ93znlQN09dqTBVcEyEjni4Yk1yKae26/OZXGdE5SX1uwf8EzTpAxNPkY9jueD8HpXol2H3PEfDY3JdZOpsa8pidS/rOxL4ddizjo3OD2q2ECy6JZoscM4BbJtYubnR8gAGdi/l7ZRM9MnT2MOfmOyBnGv3xfiGYZQu2bXtm+2KihB5tjHZiAlbZD/ryrD4Cxz1e5yroEhHm1YaVs8gOZ978fkTnyrDxmWLJL6PZGg/Yip7VUdyVevpl5RHSPkMzChTt37JhvZBAdL1eu8zYtoFYeBwd3sWR+cG3PjSa/XBFc4VMNh8rhklUZNCppJkMGpAHqD5emw=

before_deploy:
- openssl aes-256-cbc -K $encrypted_acccd17d9aaf_key -iv $encrypted_acccd17d9aaf_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after . tester@217.70.189.97:/var/www/html/bms_public_site
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false